name: ğŸ§ª Test PR from fork

on:
  pull_request_target:
  workflow_call:
    secrets:
      SESSION_SECRET:
        required: true
      SUPABASE_ANON_PUBLIC:
        required: true
      SUPABASE_SERVICE_ROLE:
        required: true
      SUPABASE_URL:
        required: true
      SERVER_URL:
        required: true
      DATABASE_URL:
        required: true

jobs:
  authorize:
    environment: ${{ github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository &&
      'external' || '' }}

    runs-on: ubuntu-latest
    steps:
      - run: echo âœ“

  lint:
    needs: authorize
    name: â¬£ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: ğŸ“¦ Install pnpm
        run: corepack enable && corepack prepare pnpm@9.15.4 --activate

      - name: ğŸ“¥ Install deps
        run: pnpm install

      - name: ğŸ”¬ Lint
        run: pnpm turbo lint

  typecheck:
    needs: authorize
    name: Ê¦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: ğŸ“¦ Install pnpm
        run: corepack enable && corepack prepare pnpm@9.15.4 --activate

      - name: ğŸ“¥ Install deps
        run: pnpm install

      - name: ğŸ” Type check
        run: pnpm turbo typecheck

  vitest:
    needs: authorize
    name: âš¡ Vitest
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: ğŸ“¦ Install pnpm
        run: corepack enable && corepack prepare pnpm@9.15.4 --activate

      - name: ğŸ“¥ Install deps
        run: pnpm install

      - name: âš¡ Run vitest
        run: pnpm --filter @shelf/webapp test -- --run
